import fs from 'node:fs/promises';
import path from 'node:path';
import {build} from 'esbuild';
import postcss from 'postcss';
import tailwind from '@tailwindcss/postcss';
const root=process.cwd();const out=path.resolve('dist');
await fs.mkdir(out,{recursive:true});
await fs.cp('public',out,{recursive:true});
const css=(await postcss([tailwind({base:root})]).process(await fs.readFile('app/globals.css','utf8'),{from:path.join(root,'app/globals.css')})).css;
await fs.writeFile(path.join(out,'portfolio.css'),css);
await build({entryPoints:['scripts/standalone-entry.tsx'],bundle:true,minify:true,format:'iife',platform:'browser',target:['es2020'],define:{'process.env.NODE_ENV':'"production"'},tsconfig:'tsconfig.json',outfile:path.join(out,'portfolio.js')});
const articles={};for(const f of await fs.readdir('public/articles'))if(f.endsWith('.json'))articles[f.replace('.json','')]=JSON.parse(await fs.readFile('public/articles/'+f,'utf8'));
const assets=Object.fromEntries((await fs.readdir('public/assets')).map(f=>[f,'assets/'+f]));
const downloads=Object.fromEntries((await fs.readdir('public/downloads')).map(f=>[f,'downloads/'+f]));
const safe=x=>JSON.stringify(x).replace(/</g,'\\u003c');
const page=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wesley Vieira · Engineering & AI</title><meta name="description" content="Software engineering leadership, AI, public source code, original technical writing and a daily learning discipline by Wesley Vieira."><meta name="theme-color" content="#08110b"><link rel="canonical" href="https://wesleyvieira99.github.io/WVPortfolio/"><link rel="icon" type="image/svg+xml" href="favicon.svg"><link rel="stylesheet" href="portfolio.css"></head><body><div id="root"></div><noscript><main><h1>Wesley Vieira</h1><p>Software Engineering Leader. Enable JavaScript to explore the interactive portfolio.</p><a href="downloads/Wesley_Vieira_Engineering_Leader_Executive.pdf">Download the executive CV</a></main></noscript><script>window.__STANDALONE__=true;window.__ASSETS__=${safe(assets)};window.__ARTICLES__=${safe(articles)};window.__DOWNLOADS__=${safe(downloads)};</script><script src="portfolio.js" defer></script></body></html>`;
await fs.writeFile(path.join(out,'index.html'),page);await fs.writeFile(path.join(out,'.nojekyll'),'');
const data=JSON.parse(await fs.readFile('lib/portfolio-seed.json','utf8'));
console.log(`Built ${data.courses.length} courses, ${data.education.length} programs, ${Object.keys(articles).length} articles and ${data.study_routine.days.length} study days.`);
